name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Set up Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 21

      # Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # Run Maven tests
      - name: Run tests with Maven
        run: mvn -B test --file OOSDPLab4/pom.xml

  auto_merge:
    needs: run_tests
    if: ${{ github.event_name == 'pull_request' && success() }}
    runs-on: ubuntu-latest

    steps:
      - name: Merge the PR
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
